stages:
  - build
  - test
  - analysis
  - deploy

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

app:
  stage: build
  image: trion/ng-cli:latest
  before_script:
    - npm ci
  script:
    - npm run build:prod
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
  tags:
    - bluerunner

documentation:
  stage: build
  image: trion/ng-cli:latest
  script:
    - npm run generate:documentation
  artifacts:
    paths:
      - documentation/
  tags:
    - bluerunner

karma:
  stage: test
  image: trion/ng-cli-karma:latest
  script:
    - npm run test:headless
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - coverage/
  tags:
    - bluerunner

e2e:
  stage: test
  image: trion/ng-cli-e2e:latest
  script:
    - npm run e2e:headless
  tags:
    - bluerunner

lint:
  stage: analysis
  image: trion/ng-cli:latest
  script:
    - npm run lint
  tags:
    - bluerunner

sonar:
  stage: analysis
  image: trion/ng-cli:latest
  before_script:
    - npm install -g sonarqube-scanner
  script:
    - sonar-scanner
  tags:
    - bluerunner

firebase:
  stage: deploy
  image: trion/ng-cli:latest
  before_script:
    - npm install -g firebase-tools
  only:
    - master
  script:
    - firebase use --token $FIREBASE_DEPLOY_KEY default
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
  tags:
    - bluerunner
