stages:
  - build
  - test
  - analysis

app:
  stage: build
  image: trion/ng-cli:latest
  before_script:
    - npm ci
  script:
    - npm run build:prod
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
  tags:
    - bluerunner

documentation:
  stage: build
  image: trion/ng-cli:latest
  before_script:
    - npm ci
  script:
    - npm run generate:documentation
  artifacts:
    paths:
      - documentation/
  tags:
    - bluerunner

karma:
  stage: test
  image: trion/ng-cli-karma:latest
  before_script:
    - npm ci
  allow_failure: false
  script:
    - npm run test:headless
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
      - coverage/
  tags:
    - bluerunner

e2e:
  stage: test
  image: trion/ng-cli-e2e:latest
  before_script:
    - npm ci
  allow_failure: false
  script:
    - npm run e2e:headless
  tags:
    - bluerunner

lint:
  stage: analysis
  image: trion/ng-cli:latest
  before_script:
    - npm ci
  script:
    - npm run lint
  tags:
    - bluerunner

sonar:
  stage: analysis
  image: trion/ng-cli:latest
  before_script:
    - npm ci
    - npm install -g sonarqube-scanner
  script:
    - >
      sonar-scanner
      -Dsonar.projectKey=footbook
      -Dsonar.host.url=https://sonar.blueanchor.io
      -Dsonar.login=b501e16a3368551857fe80f0dd97d9321323d28e
      -Dsonar.typescript.lcov.reportPaths=coverage/lcov/lcov.info
      -Dsonar.sourceEncoding=UTF-8
      -Dsonar.sources=src/app
      -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts
      -Dsonar.tests=src/app
      -Dsonar.test.inclusions=**/*.spec.ts
      -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
  tags:
    - bluerunner
